// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MWNetworkData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MwnetworkData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MwnetworkDataRoot

@implementation MwnetworkDataRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MwnetworkDataRoot_FileDescriptor

static GPBFileDescriptor *MwnetworkDataRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MWNetworkData

@implementation MWNetworkData

@dynamic type;
@dynamic strData;
@dynamic fromUsr;
@dynamic toUsr;

typedef struct MWNetworkData__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSString *strData;
  NSString *fromUsr;
  NSString *toUsr;
} MWNetworkData__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = MWNetworkData_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MWNetworkData__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "strData",
        .dataTypeSpecific.className = NULL,
        .number = MWNetworkData_FieldNumber_StrData,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MWNetworkData__storage_, strData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromUsr",
        .dataTypeSpecific.className = NULL,
        .number = MWNetworkData_FieldNumber_FromUsr,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MWNetworkData__storage_, fromUsr),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "toUsr",
        .dataTypeSpecific.className = NULL,
        .number = MWNetworkData_FieldNumber_ToUsr,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MWNetworkData__storage_, toUsr),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MWNetworkData class]
                                     rootClass:[MwnetworkDataRoot class]
                                          file:MwnetworkDataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MWNetworkData__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
